# Generated by Django 3.0.7 on 2024-05-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
