# Generated by Django 3.0.7 on 2024-05-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contas',
            new_name='Conta',
        ),
    ]
